## NumPy

`NumPy` is used to manipulate vector and matrix data structures.

The basic object in `NumPy` is its multidimensional array (its n-dimensional `ndarray`). So, it's important to understand how to work with these objects, perform basic operations, and  apply them to real data.

Across Python's data science toolkit, the n-dimensional array is a crucial building block. For instance, many other relevant libraries are built on top of `NumPy`. An important theme is that what could be done using `for` loops (e.g., matrix products) is more aptly computed using matrix computations. `NumPy` is designed using fast C code, so you should become comfortable with thinking in terms of vectors and matrices when working in machine learning. Often, it is helpful to reason about computations starting with expressions in their indexed forms and then move to the vectorized variation. In other words, a matrix product may be better understood by first reasoning about how individual computations in the product are computed. Matrix products are relevant in machine learning because they represent transformations of data. We will talk more about this later on. For now, our focus is on gaining experience with `NumPy`.

Please see the guides available at [numpy.org](https://numpy.org) for more information.

In [1]:
import numpy as np

One of the most important concepts in working with `NumPy` is the idea of shape. When we create an array (representing a scalar (0-dimensional), vector (1-dimensional), matrix (2-dimensional), or tensor (n-dimensional)), that array has a shape or dimensionality. In `NumyPy`, dimensions are also called axes.

You can create an array in various ways. For instance, the `array` function can take a Python list and convert it into an `ndarray`. 

In [2]:
a = np.array([1, 2, 3, 4]) # a 1-dimensional array
b = np.array([[1.0, 2, 3, 4], [5, 6, 7, 8]]) # a 2-dimensional array
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # a 2-dimensional array
print(a.shape, b.shape, c.shape)

print(a.dtype) # integer
print(b.dtype) # float

(4,) (2, 4) (3, 4)
int64
float64


Indexing operations behave as expected:

In [3]:
print(b[0, 0]) # fetch the value at the 0th position of the 1st axis and the 0th position of the 2nd axis
print(b[-1, -1]) # fetch the value at the last position of the 1st axis and the last position of the 2nd axis

# note the 0-up indexing while we 1-up count the axes

b[1,1] = 10 # updates array value; set the value at index [1,1] to 1
print(b)

print(b[:, 1]) # fetch all the values along the 1st position in the 2nd axis (i.e., the second column of the matrix)

print(b[-1]) # equivalent to b[-1, :] and b[-1, ...] i.e. the last row

1.0
8.0
[[ 1.  2.  3.  4.]
 [ 5. 10.  7.  8.]]
[ 2. 10.]
[ 5. 10.  7.  8.]


Here is a brief survey of some other common functionalities:

In [4]:
a = np.arange(10) # an array of 10 integers, 0-9 (analogous to Python's range)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
print(a.reshape(2, 5)) # reshape array
print(a) # original array

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(a.ndim) # 2 axes

1


In [7]:
print(np.zeros((2, 3))) # an array of all 0s
print(np.ones((2, 3))) # an array of all 1s

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.random.randn(3, 4)) # random module provides functions to create ndarrays with random values

[[ 1.02662867  0.58834094 -0.78392774 -0.07705042]
 [-1.62968761  0.64485331  0.09004603 -0.67053461]
 [ 0.78477075  0.24791341  0.42043422 -0.45950193]]


In [12]:
print(np.linspace(0, 1, 100)) # an array with 100 evenly-spaced numbers, from 0 to 1

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [13]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3,4]])

In [14]:
print(A)
print(A*B) # Hadamard/element-wise product

print(A@B) # matrix product
print(A.dot(B)) # matrix product

[[1 1]
 [0 1]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [15]:
print(A.sum()) # sum over all elements
print(A.min()) # min over all elements
print(A.max()) # max over all elements

3
0
1


In [16]:
print("apply operation across the row direction", A.sum(axis=0)) # sum of each column, i.e. operation applied across the direction along the rows

print("apply the operation across the column direction", A.sum(axis=1)) # sum of each row, i.e. operation applied across the direction along the columns

apply operation across the row direction [1 2]
apply the operation across the column direction [2 1]


In [17]:
print("concat", np.concatenate((A, B), axis=0)) # concatenate along rows
print("concat shape", np.concatenate((A, B), axis=0).shape)

q1 = np.empty((3, 4)) # creates a (3,4) array from values in memory
q2 = np.empty((3, 4))
print("stack", np.stack((q1, q2))) # stack two arrays of the same shape to create a (2, 3, 4) array

concat [[1 1]
 [0 1]
 [2 0]
 [3 4]]
concat shape (4, 2)
stack [[[ 1.02662867  0.58834094 -0.78392774 -0.07705042]
  [-1.62968761  0.64485331  0.09004603 -0.67053461]
  [ 0.78477075  0.24791341  0.42043422 -0.45950193]]

 [[ 1.02662867  0.58834094  0.78392774  0.07705042]
  [ 1.62968761  0.64485331  0.09004603  0.67053461]
  [ 0.78477075  0.24791341  0.42043422  0.45950193]]]


In [18]:
B = np.arange(3)
print("exponential applied to each element", np.exp(B)) # exponential function applied to each

exponential applied to each element [1.         2.71828183 7.3890561 ]


In NumPy, a one-dimensional array is interpreted as just that—an array with a single dimension. In other words, there's no notion of row or column arrays.

In [19]:
a = np.array((1,2,3))
print(a.T)
print(a.shape)
b = a[np.newaxis, :] # creates a new axis, with the original data along the second one (row vector)
print(b)
print(b.shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
